/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type LabelAlign = "left" | "right";
export type RuleType =
  | "string"
  | "number"
  | "boolean"
  | "method"
  | "regexp"
  | "integer"
  | "float"
  | "object"
  | "enum"
  | "date"
  | "url"
  | "hex"
  | "email";

export interface CoreSchemaForJsonBasedWesForm {
  $schema?: string;
  /**
   * 表单静态参数
   */
  formProps?: {
    colon?: boolean;
    labelAlign?: LabelAlign;
    labelWrap?: boolean;
    labelCol?: LabelCol;
    size?: "small" | "middle" | "large";
    /**
     * 列布局，针对‘标准’尺寸屏幕 / 待讨论
     */
    columns?: "1" | "2" | "3" | "4";
    preserve?: boolean;
    layout?: "horizontal" | "vertical" | "inline";
    [k: string]: unknown;
  };
  /**
   * 表单字段
   */
  fields?: {
    [k: string]: Field;
  };
}
export interface LabelCol {
  [k: string]: unknown;
}
/**
 * 定义一个表单字段
 */
export interface Field {
  /**
   * 区块开始
   */
  section?: {
    title?: string;
    description?: string;
    [k: string]: unknown;
  };
  /**
   * 数据格式：系统会默认根据这个值选择合适的组件，如果不满足需要使用 component 声明
   */
  type:
    | "number"
    | "text"
    | "integer"
    | "money"
    | "date"
    | "datetime"
    | "time"
    | "month"
    | "bool"
    | "email"
    | "url"
    | "phone"
    | "object"
    | "map"
    | "array";
  colon?: boolean;
  hidden?: boolean;
  noStyle?: boolean;
  labelAlign?: LabelAlign;
  labelCol?: LabelCol;
  /**
   * 字段的 key，同表单内唯一，系统会自动处理数据的层级
   */
  name?: string;
  /**
   * 字段值为枚举类型时设置该选项，配置一个 key-value 结构，key 作为值的选项，value 作为显示文本， 默认系统帮助使用 Select 控件；如果值类型为 array，则使用 Select 的多选功能
   */
  enum?: {
    [k: string]: unknown;
  };
  component?:
    | string
    | {
        /**
         * 组册的组件名
         */
        name?: string;
        /**
         * 组件执行时传入的静态参数
         */
        props?: {
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
  /**
   * 对字段的声明验规则
   */
  validator?: {
    /**
     * /待确认 触发校验的时机
     */
    trigger?: "blur" | "change" | "submit";
    /**
     * 具体的规则列表
     */
    rules?: Rule[];
    [k: string]: unknown;
  };
  /**
   * 字段的名称，未设置表示不显示 label 占位
   */
  label?: string;
  /**
   * 帮助信息，对字段提供详细解释
   */
  tooltip?: string;
  /**
   * 设置只读
   */
  readonly?: boolean;
  /**
   * 是否禁用
   */
  disabled?: boolean;
  /**
   * 是否必填：设置为 true 时会默认帮用户加入 required 检验规则
   */
  required?: boolean;
  /**
   * 默认值，todo
   */
  default?: {
    [k: string]: unknown;
  };
  placeholder?: string;
  /**
   * 控件的静态参数
   */
  wrapperProps?: {
    [k: string]: unknown;
  };
  /**
   * 如果 type 是 map 或者 array，需要在此定义内部结构
   */
  struct?: Field[];
  [k: string]: unknown;
}
export interface Rule {
  /**
   * 注册过的校验规则名
   */
  name?: string;
  warningOnly?: boolean;
  len?: number;
  max?: number;
  message?: string;
  min?: number;
  required?: boolean;
  type?: RuleType;
  whitespace?: boolean;
  [k: string]: unknown;
}
